### ISSUE TITLE
Diagram javítások

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#102]
A végsö beadandóban a következö diagramokat kell javítani

Követelmények, projekt, funkctionalitás: use-case (nem teljesen szabványos, nem kell mentés)

PR #123 eléggé felborítja a korábbi osztály- és szekvenciadiagramokat

**Comment by Gustorn** [comment]
Direkt volt nyitva az issue, @gregory094 azt mondta, hogy a végsö beadandóban kell csak kijavítani azokat az UML diagramokat, amikben hiba volt. Ebben az issueban lesznek felsorolva, azok, amiket a végén javítani kell.

**Comment by nyari** [comment]
Jah... Jól van rendben. :) Nem figyeltem, hogy az utolsó Milestone-hoz van
berakva. :)

2015-03-02 19:57 GMT+01:00 Gustorn <notifications@github.com>:

**Comment by Gustorn** [comment]
Fuck this issue
