### ISSUE TITLE
Korlátozások

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#11]
Az elkészítendő szoftverre vonatkozó – általában nem funkcionális - előírások, korlátozások.

**Comment by istvanszoke** [comment]
NEM KELL ELOLVASSÁTOK (csak magamnak jegyzet)

A labor gepen műkodnie kell, nem szabad akadnia a kepnek, hasonlo jelleg}u dolgokra kell
gondolni

1.4 Major constraints
 Any business or product line constraints that will impact the manner in which the system is to be specified, designed, implemented or tested are noted here.
