### ISSUE TITLE
Korábbi hetek javítása

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#125]
Ezen a héten eléggé belenyúltunk a designba, változtak a korábbi hetek szekvencia és osztálydiagramjai is (PR #123). Csak azért nyitom az issue-t, hogy ne felejtsük meg beleírni.

**Comment by gregory094** [comment]
Ezzel mi lett? :D

**Comment by Gustorn** [comment]
Semmi :D

**Comment by gregory094** [comment]
:-1

**Comment by gregory094** [comment]
+1

**Comment by Gustorn** [comment]
De nem olyan nagy probléma, a jövöheti leadásba még belefér a javítások nagy része.
