### ISSUE TITLE
Fájllista

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#133]
Ennek tartalmaznia kell leltárszerűen az egyes fájlok pontos nevét, méretét byte-ban, keletkezési idejét, valamint azt, hogy a fájlban mi került megvalósításra.

**Comment by Gustorn** [comment]
Fájl lista path szerint ABC sorrendben, git szerinti keletkezési idö: [gist](https://gist.github.com/Gustorn/2aa3ac004b4f14327ca9). Most úgy van írva, hogy `./lib`-böl kelljen futtatni, de csak a `cd`-t kell az elején javítani (úgy érdemes, hogy gyökérkönyvtárból futtatjuk).

**Comment by gregory094** [comment]
:D

**Comment by Gustorn** [comment]
Mondjuk így belegondolva formázhatnám rögtön LaTeX formátumra is...

**Comment by gregory094** [comment]
Ha nincs vele szopás... csináljad.

**Comment by Gustorn** [comment]
Ugyanabban a [gistben](https://gist.github.com/Gustorn/2aa3ac004b4f14327ca9) `file_list_latex.sh` néven. Valamit kéne csinálni a rohadt hosszú elérési útvonalakkal (aminek szerintem lenne értelme, az egy külön generált fájllista `src/main` és `src/test`-nek, úgy, hogy lényegében azokat tekintjük gyökérkönyvtárnak.

**Comment by Gustorn** [comment]
Pr #139-ben pusholtam a scripteket
