### ISSUE TITLE
Futtatás

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#134]
A futtatható kód elindításával kapcsolatos teendők leírása. Az indításhoz csak a 2. Követelmények c. dokumentumban leírt környezetet szabad előírni.

**Comment by Gustorn** [comment]
Ez most Windows parancssorból egy `./gradlew.bat run`.

**Comment by gregory094** [comment]
:+1:

**Comment by Gustorn** [comment]
FONTOS: `./gradlew -q run` a jó parancs.
