### ISSUE TITLE
Értékelés

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#135]
A projekt kezdete óta az értékelésig eltelt időben tagokra bontva, százalékban.

**Comment by gregory094** [comment]
| Leadandó sorszáma | Megszerezhető pontok | Megszerzett pontok  | Megszerezhető pontok 1 főre  | Megszerzett pontok 1 főre | Hatásfok |
|-----------------|--------------------------------|----------------------------|---------------------------------------|------------------------|-------------|
|1 | 10 | 8 | 2.5 | 2 | 80% |
|2 | 20 | 15 | 5 | 3.75 | 75% |
| 3 | 30 | 24 | 7.5 |  6 | 80% |
| 4 | 20 | 14 | 5 | 3.5 | 70% |  
| SUM | 80 | 61 | 20 | 15.25 | 76.25% |

**Comment by gregory094** [comment]
Ellenvetés?

**Comment by istvanszoke** [comment]
None
