### ISSUE TITLE
Erőforrásokkal kapcsolatos követelmények

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#14]
A szoftver fejlesztésével és használatával kapcsolatos számítógépes, hardveres, alapszoftveres és egyéb architekturális és logisztikai követelmények.

Fejléc: Azonosító Leírás Ellenőrzés Prioritás Forrás Komment

**Comment by Gustorn** [comment]
Ki milyen IDE-t / szövegszerkeszöt / egyebet fog használni, amiket ide fel lehetne sorolni?

**Comment by nyari** [comment]
vim, gedit, texstudio, intellij idea, eclipse

**Comment by nyari** [comment]
zsh kimaradt

**Comment by Gustorn** [comment]
zsh részletességig talán nem kéne belemenni. Fö editorok/IDEk, JDK, minimális rendszerkövetelmények szerintem elég.
Így akkor eddig lenne:

* Git
* GitHub
* TravisCI
* Coverity
* Waffle IO
* JDK 6+
* JRE 6+
* Gradle
* Vim
* Eclipse
* IntelliJ Idea
* TeXStudio
* Visual Paradigm
* JRE6 futtatásához elegendö minimális rendszerkövetelmények

Egyéb ötletek?

**Comment by gregory094** [comment]
Teljesen korrektnek tartom a felsorolást. Drone.io-t még használok, azt helykitöltőnek beírnám. A "megfelelő perifériák" vicces... látom @Gustorn ráérzett az ízére. 
Én még ZSH-t beleírnám, hisz vim-zsh-git -et használok pl én.

**Comment by Gustorn** [comment]
Én is zsh-t használok, inkább azt tartom kérdésesnek, hogy mennyire mélyen menjünk bele: ennyi erövel odaírhatnám bash-t (ha azt használ valaki), Windows parancssort, oprendszert, stb. Ha az az általános vélemény, hogy shelleket még írjam oda, akkor OK.
