### ISSUE TITLE
Komment lefoglalások

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#140]

**Comment by istvanszoke** [comment]
Csinálom a field package-t

**Comment by gregory094** [comment]
Ezmiez?

**Comment by istvanszoke** [comment]
Kiosztottuk ki mit kommentel. Az a lenyeg, hogy a kommenteket csak a
commenting branchbe írjuk egyelőre ne a masterbe.

**Comment by Gustorn** [comment]
Mivel nem nagyon használta senki az issue-t, ezért closeolon. A kommenteket majd kiosztjuk szóban.
