### ISSUE TITLE
Átadással kapcsolatos követelmények

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#15]
A szoftver átadásával, telepítésével, üzembe helyezésével kapcsolatos követelmények.

Fejléc: Azonosító Leírás Ellenőrzés Prioritás Forrás Komment

**Comment by istvanszoke** [comment]
Deployment diagram

**Comment by Gustorn** [comment]
Elözö évi megoldásokat elnézve ide csak a táblázat kitöltése kell, nem pedig deployement diagram.

**Comment by Gustorn** [comment]
@nyari konzultációs leírása alapján annyi kérdésem lenne, hogy akkor most lényegében copy-pasteljem be az összes leadási/bemutatási idöpontot, és ezeket egészítsem ki még egyéb dolgokkal? Vagy csak hagyjuk a 3 fontosabb milestone-t (skeleton, proto, graf)?
