### ISSUE TITLE
Egyéb nem funkcionális követelmények

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#16]
A biztonsággal, hordozhatósággal, megbízhatósággal, tesztelhetőséggel, a felhasználóval kapcsolatos követelmények.

Fejléc:

Azonosító Leírás Ellenőrzés Prioritás Forrás Komment

**Comment by Gustorn** [comment]
Azonosító formátum: NF00x

**Comment by istvanszoke** [comment]
Kérdés: Csak a fent említett nem funkcionális követelményeket fejtsem ki, vagy többet is?

**Comment by Gustorn** [comment]
Nem tudom, mit értesz fent említettek alatt, de én arra szavazok, hogy csak azokat fejtsd ki, amiknél tényleg van követelmény: biztonsággal kapcsolatos pl. szerintem nem lesz (de javítson ki bárki, ha nem ért egyet).

**Comment by istvanszoke** [comment]
Arra gondolok, amit kommentben megadtak: "A biztonsággal, hordozhatósággal,
megbízhatósággal, tesztelhetőséggel, a felhasználóval kapcsolatos
követelmények."

Biztonsággal kapcsolatos követelményekhez egy ilyen definíciót találtam:

Non-functional security requirement
 An emergent property of the system required to ensure
fulfillment of requirements in the face of abuse or misuse

Ez alapján eddig ezeket írtam össze mint biztonsági követelmények

Egy elmentett jatekot ne lehessen felulirni.
Csak a jatek iranyitasara kijelolt eger es billentyukombinaciokat lehessen
hasznalni
A robotok ne legyenek kepesek mas robotokat iranyitani.
Minden terület, ami nem a pályán van (legyen az látható vagy nem látható),
pályán kívülinek tekintendő.
Egy adott időpontban csak egy fegyvert lehessen használni.


2015. február 20. 15:44 Gustorn írta, <notifications@github.com>:

**Comment by Gustorn** [comment]
Nekem biztonsággal kapcsolatos követelményekkel kapcsolatban nem igazán ez jut eszembe, ezek nekem inkább a funkcionális kategóriába tartoznak. 
Biztonsággal kapcsolatos szerintem az lenne, ha pl. felh. neveket / jelszavakat tárolunk akkor azt nem plain textben hanem valamilyen normális cryptoval tesszük. Vagy pl. garantálni kéne, hogy nem lesz buffer over/underflow a programban (JVM-ben nincs sok értelme). Pont ezért szerintem ránk a biztonsági követelmények nem igazán vonatkoznak: nincs hálózati része a dolognak, tehát azzal nem kell foglalkozni, a hagyományos biztonsági problémák nagy része meg a választott nyelv miatt fel se merül.

**Comment by istvanszoke** [comment]
Kihagytam a secreq-eket. Toltam egy pull requestet. Valaki nézze meg pls
