### ISSUE TITLE
Szótár

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#18]
A szótár a követelmények alapján készítendő fejezet. Egy szótári bejegyzés definiálásához csak más szótári bejegyzések és köznapi – a feladattól független – fogalmak használhatók fel. A szótár mérete kb. 1-2 oldal legyen.

**Comment by gregory094** [comment]
robot, verseny, telepes, pálya, ugrál, kiesik, szakadék, áll, helyzet, pozíció, sebesség, sebességvektor, irányítható, olajfolt, ragacsfolt, folt, olajkészlet, ragacskészlet, készlet, buff, perk, curse, aktív, passzív, tároló, használ, idő, út, győzelmi kondíciók, ágensleírók, célfüggvény, telepes, bme, java, jdk, ci, travis, github, rup, fejlesztés, bme, felhasználó, kódolás stílus, dokumentum, dokumentáció, csapda, vezérlés, JVM, játékos, RUP, út, lépés, folyamatos, diszkrét, kivételkezelés, tesztelés, játéktér, típus, minta, interface, gradle, JUnit, buildscript, integráció, architektúra, igények, felület, GUI, fegyver, támadás, veszély, lehetőség, defininíció, specifikáció, követelmény, tervezés, szoftlab, adatrejtés, polimorfizmus, cleancode, szintézis, analízis, determinisztikus, fejlesztés, leírás, deklaráció, issue, milestone, tárgyalás, vita, kapcsolattartás, szinkronizáció, lean, precíz, droneio, wiki, guidlines, automata, platform, idő, management, ütemezés, beosztás, napló, validáció, verifikáció, változás, alapkövetelmény, megbízhatóság, rugalmasság, teszteredmény, kimenet, ellenőrizhetőség, csapat, döntés, eredmény, változatosság, szabványosság, szokások, irányelvek, közösség, szórakozás, stratégia, logika, táblajáték, grid, felosztás, felelősség, elvárás, kapcsolat, öröklés, szinkron, látvány, intuitívitás, bővíthetőség, elvek, egységesség,  vik, informatika, PC, csoportmunka, JRE, test driven,  verzió kontroll, VCS, UML, Git, LaTeX, nyílt forráskód, license, LPGL, kódlefedettség, Coverity, statikus elemzés, build rendszer, artifact, leszállítás, nyereség, javadoc,  szabályok, határidő, leadás, beszámoló, bemutatás, branch, fork, push, pull-request, merge, review, kontroll, szabályozottság, transzparencia, számítógép, Linux, Windows, MacOSX, platformfüggetlen, Swing, teljesítés, pontosság, report, protípus, konzultáció, konzulens, vezető, programozás, tervezés, szoftvertechnológia, szoftver, szoftvermérnökség, VIK, mérnök, szálak, animáció, felület, funkcionalitás, osztály, objektum, sablon, OO,  keret, tesztbetét, környezet, tesztkörnyezet, lokális teszt, globális teszt, multi-platform, TTD

**Comment by gregory094** [comment]
process, lefolyás, esemény, megszakítás, jelzés, értesítés, gyártás, biztonság, komment, hibaüzenet, kivételkezelés, absztrakció, réteges szerkezet, pipeline, memento, visitor, observer, felelősségek, adatrejtés, minimalitás, felelősség-szétválasztás, osztálydiagram, szekvencia, szekvenciadiagram

**Comment by gregory094** [comment]
verzió, release, nézet, control, tárgy, fegyver, forma, grafika

**Comment by gregory094** [comment]
waffleio, kanban, kijelző, átvilágítás, átlátszóság

**Comment by istvanszoke** [comment]
Úgy érzem ezt erősen fel kell osztani magunk között...

**Comment by gregory094** [comment]
Miért kellene felosztani? :D Ez már majdnem 1 oldal.

**Comment by istvanszoke** [comment]
Közbe rájöttem, hogy csak szólista kell. Nem kellenek definíciók :D

Miért kellene felosztani? :D Ez már majdnem 1 oldal.

—
Reply to this email directly or view it on GitHub
<https://github.com/gregory094/softlab4/issues/18#issuecomment-74758831>.

**Comment by nyari** [comment]
Javaslom, hogy olvassátok el a jegyzőkönyvben amit csináltam, hogy mi a különbség az elején lévő definíciók és a szótár között

**Comment by gregory094** [comment]
Ezt nem értem Dávid... mi az, hogy ne legyenek nem definiált fogalmak? Ádámtúl úgy tudom, hogy csak szófelsorolás kell. Tévedek?
