### ISSUE TITLE
A tesztek részletes tervei, leírásuk a teszt nyelvén

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#183]
[A tesztek részletes tervei alatt meg kell adni azokat a bemeneti adatsorozatokat, amelyekkel a program működése ellenőrizhető. Minden bemenő adatsorozathoz definiálni kell, hogy az adatsorozat végrehajtásától a program mely részeinek, funkcióinak ellenőrzését várjuk és konkrétan milyen eredményekre számítunk, ezek az eredmények hogyan vethetők össze a bemenetekkel.]

8.2.1 Teszteset1
• Leírás
[szöveges leírás, kb. 1-5 mondat.]
• Ellenőrzött funkcionalitás, várható hibahelyek
• Bemenet
[a proto bemeneti nyelvén megadva (lásd előző anyag)]
• Elvárt kimenet
[a proto kimeneti nyelvén megadva (lásd előző anyag)]

**Comment by istvanszoke** [comment]
Még általam át nem gondolt esetek:
robot olajra vagy ragacsra lép
robotok ütköznek
robot vacuumra ugrik
vacuum ütközik vacuummal
pályáról lelépő robotok elakadnak.  (pályán kívüli cellák id-ját elkülönítjük?)
