### ISSUE TITLE
Projektterv

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#19]

**Comment by nyari** [comment]
I think tomorrow we should have a Hangout to discuss architectural plans, and Issues #2 and #3

**Comment by gregory094** [comment]
+1

**Comment by Gustorn** [comment]
Mik a hivatalos feladatkiosztások? Értsd: UML, kódolás, grafika, menedzsment, doksi. Mindenki írja le, szerinte rá mi vonatkozik.

**Comment by Gustorn** [comment]
Csapattag feladatkörök még kellenek

**Comment by Gustorn** [comment]
Paral Zsolt - kódolás, grafika, doksi
Ha lehet UML-ért nem akarok felelös lenni (persze ettöl függetlenül csinálom)

**Comment by istvanszoke** [comment]
Szőke-N István - grafika, doksi, uml
Bevállalom.

2015. február 21. 14:27 Gustorn írta, <notifications@github.com>:

**Comment by gregory094** [comment]
ng: grafika, kód, management, doksi

**Comment by Gustorn** [comment]
Szerintem legyen 3 szerepkör / ember... @gregory094 kód, management, doksi? Ha jól emlékszem a Swing nem a kedvenced.

**Comment by gregory094** [comment]
jaaa :D bocs :D grafika alatt mást értettem

**Comment by nyari** [comment]
nyari: doksi, kód, uml
