### ISSUE TITLE
Követelmény, projekt, funkcionalitás - Leadás

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#2]
A feladat leadása.

**Comment by nyari** [comment]
Has everyone downloaded VisualParadigm already? 
Are we going to include the it project files to Git repo or handle them separately, since they are binaries. 
Evidently the exports will be EPS so we can use them in LaTeX

**Comment by Gustorn** [comment]
My vote is for as few porject files as possible. Unless it's really inconvenient to work without them, I say let everyone manage their own project files.

**Comment by nyari** [comment]
Okay. VisualParadigm has a feature to export to XML and then import from it. How about that?

**Comment by nyari** [comment]
Please write this in your calendar, @gregory094, @istvanszoke and @Gustorn 
The document should be finished by 18:00. Because I'll have to go and print it out somewhere. So please try to keep this deadline.

**Comment by gregory094** [comment]
Please give us exact coords.
