### ISSUE TITLE
TravisCI buildscript

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#21]

**Comment by gregory094** [comment]
TravisCI errored for - Merge pull request #31 from gregory094/issue#20. Builds passed but global flag is grey. Could u check please?

**Comment by gregory094** [comment]
Rebuild solved the issue.

**Comment by Gustorn** [comment]
This is incredibly strange, this just happened again. Travis clearly shows that the last build for `master` is successful, but still the global flag grey. Force rebuilding the latest commit in `master` solves the issue, which probably means it's on Travis's end.
