### ISSUE TITLE
Result.debug kimeneti nyelvesites

### ISSUE THREAD

**Issue by istvanszoke** [gregory094/softlab4#220]

**Comment by Gustorn** [comment]
?? A result konkrétan azokat a messageket printeli, amiket belepusholsz. Ezen nem kell semmit dokumentálni.

**Comment by istvanszoke** [comment]
Nem, a kódban kell változtatni. Értsd:
result.pushDebug("Changed speed for " + element + ", new speed is: " +
newSpeed.getMagnitude());

helyett

result.pushDebug("sebvalt 0 " + element + " " +  newSpeed.getMagnitude());


2015. április 19. 16:03 Gustorn írta, <notifications@github.com>:

**Comment by Gustorn** [comment]
Bocs, félreértettem.

**Comment by istvanszoke** [comment]
Adódott egy kis probléma. Oil.ontick-ből és Sticky.visit(Robot)-ból, hogyan
pusholok Resultba? Buff implements Feedback és akkor a Logger.log()-t az
ontickből meg a visitből hívnánk, nem tűnik szép megoldásnak, de mást nem
nagyon találok.

2015-04-19 16:46 GMT+02:00 Gustorn <notifications@github.com>:

**Comment by istvanszoke** [comment]
Ja és a STEP_HEARTBEAT proto parancsot meg kéne csinálni a
ProtoCommandContorllerben

2015. április 19. 17:39 István Szőke-N írta, <istvan.szoken@gmail.com>:

**Comment by istvanszoke** [comment]
@Gustorn

2015. április 19. 17:41 István Szőke-N írta, <istvan.szoken@gmail.com>:

**Comment by Gustorn** [comment]
Oilban hagy a resultot, csak írj stdout-ra
