### ISSUE TITLE
Static analysis and additional code coverage tools

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#24]
Should we have any of these in addition to Travis? 

Possible options are: [Code Climate](https://codeclimate.com/), [Coveralls](https://coveralls.io/), [Coverity](http://www.coverity.com/).

Out of these possibilities Coverity is probably the most well-known, and it offers some handy integration with Travis.

**Comment by gregory094** [comment]
Of course, we should. I vote for Coverirty. I think it's up to you to configure and make it work.

**Comment by Gustorn** [comment]
So, there are several steps to integrating Travis with Coverity, the main one being the creation of a seperate branch `coverity_scan`. Merges to this branch automatically trigger static analysis, so it should only be used after major(ish) merges. It also requires you to explicitly register the project on their site, too.

Additionally we should probably run static analysis on this repo, running it for all the forks seems a bit of an overkill...

So go for it or no?

**Comment by gregory094** [comment]
converity_scan branch seems to be a sane option. go for it!

**Comment by Gustorn** [comment]
I'll wait for #26 to be merged into master, so coverty_scan will have the correct .travis.yml to begin with.

**Comment by gregory094** [comment]
#26 merged to the master.

**Comment by Gustorn** [comment]
Coverity is working correctly, I don't think there's any need for any other static analysis tools for a project of this size.
