### ISSUE TITLE
A grafikus rendszer architektúrája

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#242]

**Comment by Gustorn** [comment]
Ez konkrétan egy külön rész a doksiban.

**Comment by istvanszoke** [comment]
Szerintem ide külön nem kell írni. Te már leírtad az architektúra működését én meg adós vagyok az osztálydiagrammal.

**Comment by Gustorn** [comment]
Valóban, valamiért subsectionnek néztem.
