### ISSUE TITLE
Platform specific build scripts

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#28]
Since we'll have to deploy on PCs where there's no build system installed, we'll have to write some system specific scripts (shell script  for *nix and batch for Windows) that only use `javac` to compile the code.

**Comment by gregory094** [comment]
:+1

**Comment by Gustorn** [comment]
Could anyone test the current issue#21 branch on Windows? `./gradlew test` should build the project correctly if there is a JDK in PATH. After that it can be merged into master.

**Comment by istvanszoke** [comment]
I'm on it. Even though it may take a while for me, Windows is "my
territory" I guess...

**Comment by istvanszoke** [comment]
Okay, it`s working. Sorry it took so long. I needed to understand what I am doing.

**Comment by Gustorn** [comment]
Alright, merging the issue#21 branch will close this issue. @gregory094 you can merge it whenever you want.
