### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#29]
What should we use for the general coding style for the project? I'd suggest going for the official Java guidelines, but there are still a few things to discuss. Here's my proposal:

**Encoding:** this should be obvious, but UTF-8

**Indenting:** indent and align with spaces. 4 space indent, no TABs.

**Bracket style:** K&R style, example:
````
if (cond) {
    // Statement
} else {
   // Statement
}
````
**Whitespace:** 
* use whitespace before and after control flow statements (`for`, `while`, `if`, `else`, `switch`, `try`, `catch`):
````
if (cond) {}   // Correct

if(cond) {}    // Incorrect

if (cond){}    // Incorrect
````

*  use whitespace around binary operators (`+`, `-`, `*`, `/`, `%`, `||`, `&&`, `=`, `==`, `!=`, `<`, `>`, `<=`, `>=`):
````
a + b // Correct

a+b   // Incorrect
````

* no whitespace around calls. Method arguments are separated by a comma followed by a single space (both on declaration and on the callsite).
````
foo.bar(a, b, c) // Correct

foo.bar(a,b,c)   // Incorrect
````

**Naming:** standard Java conventions: 
* classes and interfaces are `PascalCase` (with no pre or suffix for interfaces)
* methods, variables and method arguments are `camelCase` (with no distinction to `private`, `public` or `protected`)
* constants and enum members are `CONSTANT_CASE`
* generic type variables are a single capital letter

Note that with `PascalCase` and `camelCase` the casing of the original words are ignored: 
````
HttpRequest // Correct
HTTPRequest // Incorrect
````

**Comments:** Multline `/** */` (with `*` on every line) comments for JavaDoc, `//` for inline explanation
````
/**
 * My JavaDoc comment
 * that spans multiple lines 
*/

void test() {
    // Comment describing my algorithm
    while (true) {}
}
````

**General:** 
* use `@Override` on every function that you override
* don't ignore exceptions, at least log them even if you're planning to ignore it

**Debatable:**
* Maximum line length: 80 is a reasonable limit in most programming languages, but Java has incredibly long class names. Should we go for 80/100/120? 
* Simple conditional and loop statements:

1:
````
if (cond) do_something();
````

2:
````
if (cond) 
    do_something();
````

3: 
````
if (cond) {
    do_something();
}
````

I would personally prefer nr. 3. It makes the code less bug prone and basicly means that there are no special casing for any conditional statements (no arguments over what is a simple statement).

I'm sure I missed a few things, but this is a good enough overview for now, I think. Also if we manage to agree on a set of guidelines it would be advisable to share an Astyle/Uncrustify config file that everyone can use before pushing their commits.

**Comment by nyari** [comment]
I think you summed it up quite well.
There is only one thing I would like to add. That is, we should specify what fields should be mandatory in a JavaDoc comment.
I think a general explanation of the function should be mandatory. And any non self-explanatory parameters, and return value.
And also if there is the possibility of a RuntimeException occurring in a class (i.e. User Devides by Zero) should also be added. 
That is all

**Comment by gregory094** [comment]
@nyari is right. We should strictly determine the set of fields should be used with JavaDoc comment. In my opinion a function has three essential parameters that are functionality (in one sentence, no longer than 25 words), input, output, complexity.
I'd post an issue about our CleanCode guideline if its OK for you all. Though, CleanDocs would fit our project better :-1:

**Comment by gregory094** [comment]
p.s.: Maximum line width should be 120 chars long.

**Comment by nyari** [comment]
@gregory094 Complexity as an important information in JVM? Why don't we just write O(scary) everywhere? Jokes aside, adding a general explanation for input and output is a good idea.

**Comment by Gustorn** [comment]
I think complexity information for every single method is a bit of an overkill. I agree that it should be disclosed when appropriate, but making it mandatory? 
Also what fields should be mandatory in file/class level comments?
Is anyone feeling very strongly about the simple conditional statements part?

Once we settled these last few questions, I'll transfer the guidelines to the Wiki, so we can easily link it from the readme. Also I'll post an AStyle config with the relevent settings (do we want that in version control?).

**Comment by Gustorn** [comment]
So I created the Wiki page with the guidelines that we already agreed on. Now could anyone write up his thoughts about the required JavaDoc fields (with examples for the Wiki if possible). 

Also: should we include the AStyle config in the repo, or host it somewhere else?

**Comment by gregory094** [comment]
I'll sum up the mandatory javadoc fields with @Gustorn if its OK for him.
We should include an AStyle configuration file in our repo and run autoformat on it.

**Comment by Gustorn** [comment]
@gregory094 Please go ahead, and include them in the Wiki. Also where do we want to store the AStyle config file? Project root, or some subfolder?

**Comment by gregory094** [comment]
It is should be a hidden file in the root.

**Comment by Gustorn** [comment]
Wiki updated with the points discussed during the meeting.
