### ISSUE TITLE
Szakterület

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#4]
Annak megfogalmazása, hogy a kialakított szoftver mely területen használható, milyen célra.

**Comment by Gustorn** [comment]
Mire akarunk fókuszálni, arra, hogy ez végülis egy játék vagy egy tanulmányi projekt? Játék esetében a szakterületnek nincs nagyon értelme, azon kívül, hogy szórakoztatás céljából készült. Ha a tanulmányi projektet hangsúlyozzuk, akkor meg lehet jegyezni hogy a RUP fejlesztési módszer / szoftverfejlesztés bemutatása a szakterület. A harmadik lehetöség, hogy mindkettöt beleírom. Vélemények?

**Comment by gregory094** [comment]
Mindkettő. (Ez a "tanulmányi projekt" dolog nekem például nem jutott eszembe, de korrekt, jó ötlet.)
