### ISSUE TITLE
Követelmény azonosítók

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#44]
Mivel a doskiban több helyen is meg kell adni azonosítókat bizonyos követelményeknek, ezért jó lenne valamilyen egységes rendszerben megállapodni, javaslat:

Funkcionális: F00x
Eröforrásokkal kapcsolatos: E00x
Átadással kapcsolatos: A00x
Egyéb, nem funkcionális: NF00x

Egyéb javaslatok?

**Comment by nyari** [comment]
Alapvetően ez egy jó ötlet szerintem. Jobban tudunk majd vele boldogulni.

És javasolnám, hogy a \label{label} és a \ref parancsokat is használjuk
ezekkel, ezeknél pedig lehetne ez a minta:
Label lehetne a következő esetekben
Funkcionális: reqF:00x
Erőforrások: reqE:00x
Átadás: reqA:00x
Egyéb: reqNF:00x

2015-02-18 15:35 GMT+01:00 Gustorn <notifications@github.com>:

**Comment by gregory094** [comment]
:+1:

**Comment by Gustorn** [comment]
Akkor marad a következö formátum, mivel ahogy láttam LaTeX-ben a \label \ref nem igazán müködik táblázatos formában.

Funkcionális: F00x
Eröforrásokkal kapcsolatos: E00x
Átadással kapcsolatos: A00x
Egyéb, nem funkcionális: NF00x
