### ISSUE TITLE
Objektum katalógus

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#73]
Minden, a feladatban szereplő objektum rövid, egy-két bekezdés hosszú ismertetése. Meg kell jelenjen minden objektumhoz, hogy mi a felelőssége. Informális leírás, ezért nem kell foglalkozni az örökléssel, az interfészekkel, az absztrakt osztályokkal, a segédosztályokkal.

Objektumonként a felelősség formális leírása.

**Comment by gregory094** [comment]
@gregory094

**Comment by Gustorn** [comment]
package controls
=============
**interface Modifier : Observable**
**interface Modifiable : Observer**
**intreface Modification**

package agents
============

**interface Agent : Modifiable**

**Robot : Agent**
- fields
  - speed: Vector
  - field: Field

package buff
==========

**interface Buff**
-methods 
  - activateOn(Modifiable) : boolean / Exception ?

**Sticky : Buff**
**Oil : Buff**

package world
===========

**Field**
- fields 
  - agent: Agent
  - buffs: Array<Buff>

-methods
  - getDisplacement() : Displacement
  - placeBuff(Buff)

**FieldExplorer**
- fields
  - cache: Array<Field>
- methods:
  - getFields() : Array<Field>

package math
===========

**Displacement**
-fields
  - from: Field
  - to: Field

**Vector**
-fields 
  - x
  - y


----------------------------------------------------

Alternatíva: 
interface Controller : Observable
interface Controllable : Observer
interface Control
