### ISSUE TITLE
Szekvencia diagramok

### ISSUE THREAD

**Issue by gregory094** [gregory094/softlab4#76]
Inicializálásra, use-case-ekre, belső működésre. Konzisztens kell legyen az előző alfejezettel. Minden metódus, ami ott szerepel, fel kell tűnjön valamelyik szekvenciában. Minden metódusnak, ami szekvenciában szerepel, szereplnie kell a valamelyik osztálydiagramon.

**Comment by gregory094** [comment]
@szokeistvan

**Comment by nyari** [comment]
Robot.Accept
*FieldCell.Accept
*Command.Visit
OilBuff.Visit
StickyBuff.Visit
Robot.Add*
Robot.Use*
Robot.Accept(Command)
Field.Accept(Command)
