### ISSUE TITLE
Általános áttekintés

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#8]
A kialakítandó szoftver legmagasabb szintű architekturális képe. A fontosabb alrendszerek felsorolása, a közöttük kialakítandó interfészek lényege, a felhasználói kapcsolatok alapja. Esetleges hálózati és adattárolási elvárások. Nagyon velősen, félreérthetetlenül kell fogalmazni.

**Comment by gregory094** [comment]
@Gustorn
