### ISSUE TITLE
Consistent line endings

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#82]
As of now our files have inconsistent line endings (the usual `\n` for Unix and `\r\n` for Windows). The latter are really prevalent in the supplied LaTeX files. At one point this is going to generate one horrible diff (most text editors under Unix will autoconvert these, not Vim though), so my suggestion is: 

1. I'll fix up the file endings in all the relevant files by changing them to `\n`. 
2. From that point you should only check-in files with Unix style line endings, and check-out whatever format you want to use. (This is the default behaviour on Git for Windows)
3. Add a .gitattributes file that enforces this rule: [example](https://help.github.com/articles/dealing-with-line-endings/)

There's one drawback: this will nuke `git blame` for the files we've already worked on. The positive is that the number of the affected files are relatively small now, and it will help avoiding a potential problem in the future.

**EDIT:** **This ended up to be much less severe than I thought, only one file was affected, so it's pretty much a no brainer.**

**Comment by gregory094** [comment]
:+1
