### ISSUE TITLE
Funkciók

### ISSUE THREAD

**Issue by Gustorn** [gregory094/softlab4#9]
A feladat kb. 4000 karakteres (kb 1,5 oldal) részletezettségű magyar nyelvű leírása. Nem szerepelhetnek informatikai kifejezések. Lényegében ez az 5. olyan pont, ami u.a. kéri. Hosszadalmas, fájdalmas bullshitelés.

**Comment by nyari** [comment]
Bár merge-eltem de az Issue-t NEM zárom le. Szerintem a csak négy égtáj fele ugrás eléggé megöli a játékot mondjuk egy átlós szakaszon. Szerintem jobb lenne az átlós (+45° eltoáls) irányokat is belevenni. 
Várom a leszavazást. :D
@gregory094 @istvanszoke @Gustorn

**Comment by gregory094** [comment]
Tegnap @istvanszoke felvetése után, amire nem volt ellenvetés. Ezt tárgyaljuk meg.

**Comment by nyari** [comment]
Akkor én értettem félre. :/ De ha csak én voltam így ezzel akkor mehet a close.
@gregory094 @Gustorn @istvanszoke

**Comment by istvanszoke** [comment]
Amikor én ezt felvetettem, akkor még máshogy nézett ki a játéktér. Így már
én is úgy gondolom jobb lenne, ha belevennénk az átlós irányt. De ezt
később is bele tudjuk tenni, mint plusz feature nem?
